
import { Crimson_Text, Playfair_Display } from 'next/font/google'
import "./globals.css";
import Header from "@/components/header";
import Footer from '@/components/footer';

export const txtRegular = Crimson_Text({ 
  subsets: ['latin'], 
  variable: '--font-txtRegular',
  weight: [ '400','600'],
  style: ['normal', 'italic'],
  display: 'swap',

})

export const txtHeading = Playfair_Display({ 
  subsets: ['latin'], 
  variable: '--font-txtHeading',
  weight: [ '400','600','800'],
  style: ['normal'],
  display: 'swap',

})


export const metadata = {
  title: "Allan Banuelos Fotografia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${txtHeading.variable} ${txtRegular.variable}`}>
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
